### ISSUE TITLE
Support the mongodb driver?

### ISSUE THREAD

**Issue by Andrewangeta** [m-barthelemy/vapor-queues-fluent-driver#1]
Any plans to support the mongoldb fluent driver? I'd be open to help if this is a plan for the future.

**Comment by m-barthelemy** [comment]
Hi Andrew, as discussed together on Discord: it's probably not possible to support Mongo without importing the `fluent-mongo-driver` package.

This driver tries to avoid any direct dependency on any database-specific package, it only uses Fluent and SQLKit to build the SQL queries, meaning that it can only support engines who have a SQL based dialect interface.

If you decide to start your own Queues driver for mongo I'll be happy to help!
