### ISSUE TITLE
Bug in Listing jobs

### ISSUE THREAD

**Issue by thuotdwz** [m-barthelemy/vapor-queues-fluent-driver#5]
Hi, great package! However there is a small bug in the Listing jobs from the readme with this line:

    let queue = req.queue as! FluentQueue

This receives an error that FluentQueue is not available, because it is not marked public?

**Comment by m-barthelemy** [comment]
Thanks for reporting this!
Fixed in https://github.com/m-barthelemy/vapor-queues-fluent-driver/releases/tag/0.3.5
