### ISSUE TITLE
dbType property of FluentQueuesDriver is not used code

### ISSUE THREAD

**Issue by thuotdwz** [m-barthelemy/vapor-queues-fluent-driver#7]
While I was looking at issue #5 I also noticed The dbType of FluentQueuesDriver is not used by any code. It is also defaulting to .postgresql, which might cause confusion to developers who think they need to set the database id parameter.

Maybe dbType parameter should be removed from the constructor of FluentQueuesDriver ?

Thank you!

**Comment by m-barthelemy** [comment]
Thanks for the feedback!
`dbType` is used to initialize `FluentQueue`, and later to select the exact SQL to send to the database driver.
But I agree that the way it's currently done is confusing.
I'll make an update soon and will hopefully do a bit of cleanup there.

**Comment by m-barthelemy** [comment]
Ok I saw what you meant, thanks for reporting this!
Cleanup done in https://github.com/m-barthelemy/vapor-queues-fluent-driver/tree/0.3.6
